apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone-delivery.mongoServiceName" . }}
  labels:
    {{- include "drone-delivery.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.auth.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.auth.password | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongo.auth.database | quote }}
