namespace: drone-delivery-dev

mongo:
  auth:
    password: dev-change-me

workloads:
  auth-service:
    image: docker.io/khiempg225868/auth-service:v1.0.3
  delivery-service:
    image: docker.io/khiempg225868/delivery-service:v1.0.3
  order-service:
    image: docker.io/khiempg225868/order-service:v1.0.3
  notification-service:
    image: docker.io/khiempg225868/notification-service:v1.0.3
  python-optimizer:
    image: docker.io/khiempg225868/python-optimizer:v1.0.3
  frontend:
    image: docker.io/khiempg225868/frontend:v1.0.3
    enabled: true
    serviceType: NodePort
