namespace: drone-delivery

mongo:
  auth:
    password: prod-change-me

workloads:
  auth-service:
    replicas: 2
    image: docker.io/khiempg225868/auth-service:v2.0.1
  delivery-service:
    replicas: 2
    image: docker.io/khiempg225868/delivery-service:v2.0.1
  order-service:
    replicas: 2
    image: docker.io/khiempg225868/order-service:v2.0.1
  notification-service:
    replicas: 2
    image: docker.io/khiempg225868/notification-service:v2.0.1
  python-optimizer:
    image: docker.io/khiempg225868/python-optimizer:v2.0.1
  frontend:
    image: docker.io/khiempg225868/frontend:v2.0.1
    enabled: true
    serviceType: NodePort