namespace: drone-delivery-dev

mongo:
  auth:
    password: dev-change-me

workloads:
  auth-service:
    image: docker.io/khiempg225868/auth-service:v2.0.4
  delivery-service:
    image: docker.io/khiempg225868/delivery-service:v2.0.4
  order-service:
    image: docker.io/khiempg225868/order-service:v2.0.4
  notification-service:
    image: docker.io/khiempg225868/notification-service:v2.0.4
  python-optimizer:
    image: docker.io/khiempg225868/python-optimizer:v2.0.4
  frontend:
    image: docker.io/khiempg225868/frontend:v2.0.4
    enabled: true
    serviceType: NodePort
