apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: drone-delivery
  namespace: argocd
spec:
  description: GitOps project for the drone delivery thesis
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
